// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoliceOp.API.Data;

namespace PoliceOp.API.Migrations
{
    [DbContext(typeof(PoliceOpAPIContext))]
    [Migration("20210526190248_Classes Redone")]
    partial class ClassesRedone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PoliceOp.Models.AvisRecherche", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("datetime2");

                    b.Property<string>("Informations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatutRecherche")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UID");

                    b.ToTable("AvisRecherches");
                });

            modelBuilder.Entity("PoliceOp.Models.Personne", b =>
                {
                    b.Property<int>("PersonneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BiometrieID")
                        .HasColumnType("int");

                    b.Property<string>("CouleurCheveux")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouleurYeux")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IFU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LieuNaissance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NPI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationalite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Personne_mere")
                        .HasColumnType("int");

                    b.Property<int?>("Personne_pere")
                        .HasColumnType("int");

                    b.Property<byte[]>("Photographie")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResidenceId")
                        .HasColumnType("int");

                    b.Property<int>("Sexe")
                        .HasColumnType("int");

                    b.Property<string>("SignesParticuliers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituationMatrimoniale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Taille")
                        .HasColumnType("float");

                    b.Property<string>("Teint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersonneId");

                    b.HasIndex("Personne_mere");

                    b.HasIndex("Personne_pere");

                    b.ToTable("Personnes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Personne");
                });

            modelBuilder.Entity("PoliceOp.Models.Requete", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateRequete")
                        .HasColumnType("datetime2");

                    b.Property<string>("TermeRequete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UID");

                    b.ToTable("Requetes");
                });

            modelBuilder.Entity("PoliceOp.Models.Session", b =>
                {
                    b.Property<Guid>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SessionID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("PoliceOp.Models.Agent", b =>
                {
                    b.HasBaseType("PoliceOp.Models.Personne");

                    b.Property<string>("Corps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Agent");
                });

            modelBuilder.Entity("PoliceOp.Models.PersonneSpeciale", b =>
                {
                    b.HasBaseType("PoliceOp.Models.Personne");

                    b.HasDiscriminator().HasValue("PersonneSpeciale");
                });

            modelBuilder.Entity("PoliceOp.Models.Proprietaire", b =>
                {
                    b.HasBaseType("PoliceOp.Models.Personne");

                    b.HasDiscriminator().HasValue("Proprietaire");
                });

            modelBuilder.Entity("PoliceOp.Models.Operateur", b =>
                {
                    b.HasBaseType("PoliceOp.Models.Agent");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Operateur");
                });

            modelBuilder.Entity("PoliceOp.Models.Personne", b =>
                {
                    b.HasOne("PoliceOp.Models.Personne", "Mere")
                        .WithMany()
                        .HasForeignKey("Personne_mere");

                    b.HasOne("PoliceOp.Models.Personne", "Pere")
                        .WithMany()
                        .HasForeignKey("Personne_pere");
                });
#pragma warning restore 612, 618
        }
    }
}
